name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Use PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run CI Script
        run: pnpm run ci

      - name: Create and Add Test Report to Summary
        uses: test-summary/action@v2
        with:
          paths: "*junit.xml"
        if: success() || failure()

      - name: Create Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/cobertura-coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds:
        if: success() || failure()

      - name: Add Code Coverage Report to Summary
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
        if: success() || failure()

      - name: Upload Coverage Reports to Codecov
        uses: codecov/codecov-action@v3
        if: success() || failure()
