name: Lint & Test Package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Lint Package
        run: npm run lint
        if: success() || failure()

      - name: Test Package
        run: npm run test
        if: success() || failure()

      - name: Build Package
        run: npm run build
        if: success() || failure()

      - name: Upload Package Artifact
        uses: actions/upload-artifact@v3
        with:
          name: regexp-ts
          path: dist/**/*
        if: success() || failure()

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "*junit.xml"
        if: success() || failure()

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/cobertura-coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds:
        if: success() || failure()

      - name: Code Coverage Summary
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
        if: success() || failure()
